version: '3.3'

services:
  db:
    container_name: CleanArchDb
    image: postgres
    environment:
      POSTGRES_PASSWORD: CleanArchDb
      POSTGRES_USER: CleanArchDb
      POSTGRES_DB: CleanArchDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres:/var/lib/postgresql/data